#Clear data in global environment
rm(list=ls())

#Load Hmisc library for its labeling functionality
library(Hmisc)

#Load data (update path_to_data before running)
path_to_data <- '../data-csv/cog_adrcpathnacc.csv' 

data=read.csv(path_to_data)

#Set variable labels
label(data$id_addi)="Masked Participant ID for ADDI"
label(data$cdagedx)="Age of DX of cog impairment"
label(data$cdageos)="Age of onset of cog impairment"
label(data$cdpos)="Pattern of onset"
label(data$cdprog)="Pattern of progression"
label(data$nac1)="Responses based on"
label(data$nac10)="Undetermined etiology"
label(data$nac10a)="Undetermined etiology - If present"
label(data$nac11)="Frontotemporal dementia"
label(data$nac11a)="Frontotemporal dementia - If present"
label(data$nac12)="Primary progressive aphasia"
label(data$nac12a)="Primary progressive aphasia - If present"
label(data$nac12a1)="Progressive nonfluent aphasia (1=present, 0-=absent)"
label(data$nac12a2)="Semantic dementia (1=present, 0-=absent)"
label(data$nac12a3)="Semantic dementia - variant (1=present, 0-=absent)"
label(data$nac12a4)="Other (1=present, 0-=absent)"
label(data$nac13)="Progressive supranuclear palsy"
label(data$nac13a)="Progressive supranuclear palsy - if present"
label(data$nac14)="Corticobasal degeneration"
label(data$nac14a)="Corticobasal degeneration - if present"
label(data$nac15)="Huntington's"
label(data$nac15a)="Huntington's - if present"
label(data$nac16)="Prion disease"
label(data$nac16a)="Prion disease - if present"
label(data$nac17)="Cognitive dysfunction meds"
label(data$nac17a)="Cognitive dysfunction meds - if present"
label(data$nac18)="Cognitive dysfunction medical illness"
label(data$nac18a)="Cognitive dysfunction medical illness - if present"
label(data$nac19)="Depression"
label(data$nac19a)="Depression - if present"
label(data$nac2)="Normal cog"
label(data$nac20)="Other major psychiatric illness"
label(data$nac20a)="Other major psychiatric illness - if present"
label(data$nac21)="Down's syndrome"
label(data$nac21a)="Down's syndrome - if present"
label(data$nac22)="Parkinson's disease"
label(data$nac22a)="Parkinson's disease - if present"
label(data$nac23)="Stroke"
label(data$nac23a)="Stroke - if present"
label(data$nac24)="Hydrocephalus"
label(data$nac24a)="Hydrocephalus - if present"
label(data$nac25)="Traumatic brain injury"
label(data$nac25a)="Traumatic brain injury - if present"
label(data$nac26)="CNS neolasm"
label(data$nac26a)="CNS neolasm - if present"
label(data$nac27)="Other"
label(data$nac27a)="Other - specify"
label(data$nac27as)="NAC27AS"
label(data$nac28)="ALS"
label(data$nac28a)="ALS - if present"
label(data$nac29)="HIV encephalopathy"
label(data$nac29a)="HIV encephalopathy - if present"
label(data$nac3)="Meet criteria for dementia"
label(data$nac30)="Hippocampal sclerosis"
label(data$nac30a)="Hippocampal sclerosis - if present"
label(data$nac31)="Hypoxic/anoxic"
label(data$nac31a)="Hypoxic/anoxic - if present"
label(data$nac32)="Delirium"
label(data$nac32a)="Delirium - if present"
label(data$nac33a)="Hypertension"
label(data$nac33aa)="Hypertension - if present"
label(data$nac33b)="Heart failure"
label(data$nac33bb)="Heart failure - if present"
label(data$nac33c)="Diabetes"
label(data$nac33cc)="Diabetes - if present"
label(data$nac33d)="COPD"
label(data$nac33dd)="COPD - if present"
label(data$nac33e)="Cancer"
label(data$nac33ee)="Cancer - if present"
label(data$nac33f)="Sleep apnea"
label(data$nac33ff)="Sleep apnea - if present"
label(data$nac33g)="Alcoholism"
label(data$nac33gg)="Alcoholism - if present"
label(data$nac33h)="Drug use disorder"
label(data$nac33hh)="Drug use disorder - if present"
label(data$nac33i)="Anemia"
label(data$nac33ii)="Anemia - if present"
label(data$nac33j)="Arthritis"
label(data$nac33jj)="Arthritis - if present"
label(data$nac33k)="Macular degeneration"
label(data$nac33kk)="Macular degeneration - if present"
label(data$nac33l)="Other psychiatric disorder"
label(data$nac33ll)="Other psychiatric disorder - if present"
label(data$nac34)="NAC34"
label(data$nac35)="NAC35"
label(data$nac36)="NAC36"
label(data$nac37)="NAC37"
label(data$nac38)="NAC38"
label(data$nac39)="NAC39"
label(data$nac40)="NAC40"
label(data$nac41)="NAC41"
label(data$nac4a)="Amnestic MCI - impairment only"
label(data$nac4b)="Amnestic MCI - domains"
label(data$nac4b1)="NAC4B1"
label(data$nac4b2)="NAC4B2"
label(data$nac4b3)="NAC4B3"
label(data$nac4b4)="NAC4B4"
label(data$nac4c)="Non-Amnestic MCI - single"
label(data$nac4c1)="NAC4C1"
label(data$nac4c2)="NAC4C2"
label(data$nac4c3)="NAC4C3"
label(data$nac4c4)="NAC4C4"
label(data$nac4d)="Non-Amnestic MCI - multi"
label(data$nac4d1)="NAC4D1"
label(data$nac4d2)="NAC4D2"
label(data$nac4d3)="NAC4D3"
label(data$nac4d4)="NAC4D4"
label(data$nac4e)="Impaired, not MCI"
label(data$nac5)="Prob AD"
label(data$nac5a)="Prob AD - if present"
label(data$nac6)="Possible AD"
label(data$nac6a)="Possible AD - If present"
label(data$nac7)="Demenia w/ Lewy bodies"
label(data$nac7a)="Demenia w/ Lewy bodies - If present"
label(data$nac8)="Vascular dementia"
label(data$nac8a)="Vascular dementia - If present"
label(data$nac9)="Alcohol dementia"
label(data$nac9a)="Alcohol dementia - If present"
